**`environment.yml`**
```yml
name: yt-ledger
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.23
  - pip=24.0
  - certifi=2024.7.4
  - et-xmlfile=1.1.0
  - fpdf2=2.7.9
  - openpyxl=3.1.5
  - pillow=10.4.0
  - requests=2.32.3
  - yt-dlp=2024.7.16
  - pip:
    - charset-normalizer==3.3.2
    - idna==3.7
    - urllib3==2.2.2
