# report_html.py

from pathlib import Path
from urllib.parse import quote
from datetime import datetime
import logging

def create_html_report(video_list, thumb_map, report_title, project_name, template_path, output_filename):
    """Generates the final HTML report."""
    if not video_list:
        logging.info("No video data to generate HTML report.")
        return
    logging.info("\nBuilding HTML report...")
    try:
        template_content = template_path.read_text(encoding='utf-8')
    except FileNotFoundError:
        logging.critical(f"CRITICAL ERROR: Template '{template_path}' not found.")
        return

    video_rows_html = ""
    for video_data in video_list:
        video_id = video_data.get('id')
        video_title = video_data.get('title', 'N/A')
        channel_name = video_data.get('channel', 'N/A') # Get channel name
        youtube_url = f"https://www.youtube.com/watch?v={video_id}"

        thumb_src = ""
        if video_id in thumb_map:
            try:
                relative_thumb_path = thumb_map[video_id].relative_to(output_filename.parent)
                thumb_src = quote(relative_thumb_path.as_posix())
            except Exception:
                thumb_src = quote(str(thumb_map[video_id]))

        video_path = video_data.get('video_path')
        if video_path and video_path.name != "Not Downloaded":
            absolute_path = video_path.resolve().as_uri()
            local_file_html = f'<td><a class="local-file-link" href="{absolute_path}" target="_blank">Watch Local File</a></td>'
        else:
            local_file_html = '<td>Not Downloaded</td>'

        # --- UPDATED HTML ROW ---
        video_rows_html += f"""
        <tr>
            <td><a href="{youtube_url}" target="_blank"><img src="{thumb_src}" alt="Thumbnail for {video_title}"></a></td>
            <td class="video-title">{video_title}</td>
            <td class="channel-name">{channel_name}</td>
            <td>{video_data.get('upload_date', 'N/A')}</td>
            <td class="full-url-col"><a href="{youtube_url}" target="_blank">{youtube_url}</a></td>
            {local_file_html}
        </tr>"""

    generation_date = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    footer_html = f"Generated by {project_name} on {generation_date}"
    final_html = template_content.replace('<!--REPORT_TITLE_PLACEHOLDER-->', report_title)
    final_html = final_html.replace('<!--VIDEO_ROWS_PLACEHOLDER-->', video_rows_html)
    final_html = final_html.replace('<!--FOOTER_PLACEHOLDER-->', footer_html)

    try:
        output_filename.write_text(final_html, encoding='utf-8')
        logging.info(f"✅ Success! HTML report saved as '{output_filename}'")
    except Exception as e:
        logging.error(f"❌ Error saving HTML file: {e}")
